Output demo.gif

Set Shell zsh
Set FontSize 14
Set Width 1200
Set Height 800
Set Padding 20
Set Theme "Catppuccin Mocha"

Type "quien roots.io"
Sleep 500ms
Enter
Sleep 4s

Type "d"
Sleep 3s

Type "m"
Sleep 3s

Type "s"
Sleep 3s

Type "h"
Sleep 3s

Type "e"
Sleep 3s

Type "t"
Sleep 3s

Type "w"
Sleep 2s

Type "r"
Sleep 2s
Type "r"
Sleep 1s

Type "i"
Sleep 4s
Type "w"
Sleep 1s

Type "q"
Sleep 500ms
